global:
  scrape_native_histograms: true
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
    cluster: 'porch'

scrape_configs:
  - job_name: 'porch-server'
    scrape_native_histograms: true
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: ['api.porch-system.svc.cluster.local:9464']
        labels:
          service: 'porch'

  - job_name: 'porch-controllers'
    scrape_native_histograms: true
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: ['porch-controllers.porch-system.svc.cluster.local:9464']
        labels:
          service: 'porch'

  - job_name: 'function-runner'
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: ['function-runner.porch-system.svc.cluster.local:9464']
        labels:
          service: 'function-runner'
          component: 'grpc-server'