//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2026 The kpt Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by openapi-gen. DO NOT EDIT.

package v1alpha1

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Condition) OpenAPIModelName() string {
	return "com.github.kptdev.porch.api.porch.v1alpha1.Condition"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Field) OpenAPIModelName() string {
	return "com.github.kptdev.porch.api.porch.v1alpha1.Field"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in File) OpenAPIModelName() string {
	return "com.github.kptdev.porch.api.porch.v1alpha1.File"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GitLock) OpenAPIModelName() string {
	return "com.github.kptdev.porch.api.porch.v1alpha1.GitLock"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GitPackage) OpenAPIModelName() string {
	return "com.github.kptdev.porch.api.porch.v1alpha1.GitPackage"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Locator) OpenAPIModelName() string {
	return "com.github.kptdev.porch.api.porch.v1alpha1.Locator"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NameMeta) OpenAPIModelName() string {
	return "com.github.kptdev.porch.api.porch.v1alpha1.NameMeta"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in OciPackage) OpenAPIModelName() string {
	return "com.github.kptdev.porch.api.porch.v1alpha1.OciPackage"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PackageCloneTaskSpec) OpenAPIModelName() string {
	return "com.github.kptdev.porch.api.porch.v1alpha1.PackageCloneTaskSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PackageEditTaskSpec) OpenAPIModelName() string {
	return "com.github.kptdev.porch.api.porch.v1alpha1.PackageEditTaskSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PackageInitTaskSpec) OpenAPIModelName() string {
	return "com.github.kptdev.porch.api.porch.v1alpha1.PackageInitTaskSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PackageMetadata) OpenAPIModelName() string {
	return "com.github.kptdev.porch.api.porch.v1alpha1.PackageMetadata"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PackageRevision) OpenAPIModelName() string {
	return "com.github.kptdev.porch.api.porch.v1alpha1.PackageRevision"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PackageRevisionList) OpenAPIModelName() string {
	return "com.github.kptdev.porch.api.porch.v1alpha1.PackageRevisionList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PackageRevisionRef) OpenAPIModelName() string {
	return "com.github.kptdev.porch.api.porch.v1alpha1.PackageRevisionRef"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PackageRevisionResources) OpenAPIModelName() string {
	return "com.github.kptdev.porch.api.porch.v1alpha1.PackageRevisionResources"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PackageRevisionResourcesList) OpenAPIModelName() string {
	return "com.github.kptdev.porch.api.porch.v1alpha1.PackageRevisionResourcesList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PackageRevisionResourcesSpec) OpenAPIModelName() string {
	return "com.github.kptdev.porch.api.porch.v1alpha1.PackageRevisionResourcesSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PackageRevisionResourcesStatus) OpenAPIModelName() string {
	return "com.github.kptdev.porch.api.porch.v1alpha1.PackageRevisionResourcesStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PackageRevisionSpec) OpenAPIModelName() string {
	return "com.github.kptdev.porch.api.porch.v1alpha1.PackageRevisionSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PackageRevisionStatus) OpenAPIModelName() string {
	return "com.github.kptdev.porch.api.porch.v1alpha1.PackageRevisionStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PackageSpec) OpenAPIModelName() string {
	return "com.github.kptdev.porch.api.porch.v1alpha1.PackageSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PackageStatus) OpenAPIModelName() string {
	return "com.github.kptdev.porch.api.porch.v1alpha1.PackageStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PackageUpgradeTaskSpec) OpenAPIModelName() string {
	return "com.github.kptdev.porch.api.porch.v1alpha1.PackageUpgradeTaskSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ParentReference) OpenAPIModelName() string {
	return "com.github.kptdev.porch.api.porch.v1alpha1.ParentReference"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PorchPackage) OpenAPIModelName() string {
	return "com.github.kptdev.porch.api.porch.v1alpha1.PorchPackage"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PorchPackageList) OpenAPIModelName() string {
	return "com.github.kptdev.porch.api.porch.v1alpha1.PorchPackageList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ReadinessGate) OpenAPIModelName() string {
	return "com.github.kptdev.porch.api.porch.v1alpha1.ReadinessGate"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in RenderStatus) OpenAPIModelName() string {
	return "com.github.kptdev.porch.api.porch.v1alpha1.RenderStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in RepositoryRef) OpenAPIModelName() string {
	return "com.github.kptdev.porch.api.porch.v1alpha1.RepositoryRef"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ResourceIdentifier) OpenAPIModelName() string {
	return "com.github.kptdev.porch.api.porch.v1alpha1.ResourceIdentifier"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Result) OpenAPIModelName() string {
	return "com.github.kptdev.porch.api.porch.v1alpha1.Result"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ResultItem) OpenAPIModelName() string {
	return "com.github.kptdev.porch.api.porch.v1alpha1.ResultItem"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ResultList) OpenAPIModelName() string {
	return "com.github.kptdev.porch.api.porch.v1alpha1.ResultList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in SecretRef) OpenAPIModelName() string {
	return "com.github.kptdev.porch.api.porch.v1alpha1.SecretRef"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Selector) OpenAPIModelName() string {
	return "com.github.kptdev.porch.api.porch.v1alpha1.Selector"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Task) OpenAPIModelName() string {
	return "com.github.kptdev.porch.api.porch.v1alpha1.Task"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in TaskResult) OpenAPIModelName() string {
	return "com.github.kptdev.porch.api.porch.v1alpha1.TaskResult"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in UpstreamPackage) OpenAPIModelName() string {
	return "com.github.kptdev.porch.api.porch.v1alpha1.UpstreamPackage"
}
